### PR TITLE
Format yaml

### PR DESCRIPTION
**Pull request by MemberIT**
Fix yaml format indent 4 space (python style).

### CODE REVIEW

**Comment by mrlesmithjr** [comment]
LOL. I was just cleaning up all of this as well. `master` should be good to go now.

**Comment by MemberIT** [comment]
:)

**Comment by mrlesmithjr** [comment]
So much fun! Hang tight, I am working through the Travis testing. Been meaning to get this setup anyways.

**Comment by mrlesmithjr** [comment]
@MemberIT You ran into this scenario?
```bash
dpkg: error processing package netplan.io (--configure):
 installed netplan.io package post-installation script subprocess returned error exit status 2
dpkg: dependency problems prevent configuration of nplan:
 nplan depends on netplan.io; however:
  Package netplan.io is not configured yet.
```

**Comment by mrlesmithjr** [comment]
I have everything resolved now. I will go ahead and close this, and I really appreciate your contribution.

**Comment by MemberIT** [comment]
@mrlesmithjr, thanks.
I can create new PR if it is needed.

**Comment by mrlesmithjr** [comment]
@MemberIT Nope, not necessary. Thanks again!

**Pull request closed without merging**
